# Esses arquivos acabam criando um container store-store sem uso, já que serviu apenas para fazer o build da app react.
version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile_prd
    ports:
      - "80:80"

# não uso volume pq não estou passando nada do meu host para o container
# eu copio a pasta build do node para o nginx
# se precisar escalar o serviço, você pode usar o comando docker-compose up --scale nginx=3, que iniciará três instâncias do contêiner nginx em execução simultaneamente
