# Use a imagem Node como base
FROM node:14 as builder

# Definir o diretório de trabalho
WORKDIR /store

# Copie o arquivo package.json para o contêiner
COPY package.json ./

# Instale as dependências do seu aplicativo
RUN npm install

# Copie todos os outros arquivos para o contêiner
COPY . .

# Execute o comando para construir a aplicação React
RUN npm run build

# Use a imagem oficial do Nginx como base
FROM nginx:stable-alpine

# Copie o arquivo de configuração do Nginx para o diretório padrão do Nginx
COPY /docker/nginx/nginx.conf /etc/nginx/nginx.conf

# # Copie a pasta build feito no node acima para o diretório padrão do Nginx
COPY --from=builder /store/build /usr/share/nginx/html

# Servir pasta build local direto para nginx, em vez de montar ela com node
#COPY /build /usr/share/nginx/html

# Exponha a porta 80
EXPOSE 80

# Defina a porta padrão que o contêiner deve ouvir
CMD ["nginx", "-g", "daemon off;"]